# Generated by Django 2.2.5 on 2021-08-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
